### ISSUE TITLE
Data persistence when app is updated

### ISSUE THREAD

**Issue by rclai** [TobiasHennig/loki-nativescript-adapter-example#1]
Will the database.db file get wiped out if the app is updated to the latest version? If so, does this file need to be saved somewhere else?

I used this in the telerik platform and every time I do a sync, the database.db file gets wiped.

Great plugin by the way.

**Comment by TobiasHennig** [comment]
To be honest, ... i don't know. You could choose between 3 different locations to save your data ([file-system.knowFolders](http://docs.nativescript.org/ApiReference/file-system/knownFolders/README)). This [file](https://github.com/NativeScript/sample-JustMeme/blob/master/app/shared/local-storage/local-storage.js) on the NativeScript `sample-JustMeme` repo shows the usage of local storage and online Telerik Everlive.

**Comment by rclai** [comment]
Oh cool thanks.
